name: My github Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9, 3.11]
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependecies
      run: |
        python -m pip install --upgrade pip
        pip install flask
        pip install pytest
    
    - name: Run tests
      run: |
        cd Project1
        python -m pytest app.py