# This workflow will install Python dependencies, run tests with a variety of Python versions


name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flask
        python -m pip install pytest
        
    - name: Test with pytest
      run: |
        cd Project1
        python -m pytest app.py
